apiVersion: v1
kind: Namespace
metadata:
  name: edge-demo
  labels:
    env: edge
---
apiVersion: v1
kind: Pod
metadata:
  name: hello
  namespace: edge-demo
  labels:
    app: hello
spec:
  containers:
  - name: echo
    image: hashicorp/http-echo:1.0.0
    args: ["-text=hello from edge"]
    ports:
    - containerPort: 5678
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: edge-demo
spec:
  selector:
    app: hello
  ports:
  - name: http
    port: 80
    targetPort: 5678
    nodePort: 30080
  type: NodePort

